#!/usr/bin/env bash
# This script displays numbers 1-20 with cultural "bad luck" messages
# for specific numbers (4-China, 9-Japan, 17-Italy)
count=1
while [ $count -le 20 ]
do
    echo $count
    case $count in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    count=$((count + 1))
done
